# Generated by Django 5.2.13 on 2026-05-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='core_attend_date_3e9c6b_idx',
            old_name='core_attend_date_4a6c3f_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='core_attend_date_970a68_idx',
            old_name='core_attend_date_9b0b6b_idx',
        ),
    ]
